variables:
  CMakeConfig: -G "Visual Studio 16 2019" -A x64
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - package

build_release:
  tags:
  - windows
  - amd64
  stage: build
  script:
  - 'cmake -S . -B build %CMakeConfig%'
  - 'cmake --build build --config Release'
  artifacts:
    paths:
    - bin/

package_release:
  tags:
  - windows
  - amd64
  stage: package
  dependencies:
    - build_release
  script:
    - echo "Packaging build"
    - copy bin\Release\FidelityFX_CLI.exe .
  artifacts:
    name: "FidelityFX_CLI-%CI_COMMIT_TAG%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
    paths:
    - "FidelityFX_CLI.exe"
    - "README.md"
    - "license.txt"